name: flutter_tmdb_movie
description: Flutter Movie App Using TMDB API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  intl: ^0.17.0
  get_it: ^7.2.0
  dio: ^4.0.6
  easy_localization: ^3.0.0
  eva_icons_flutter: ^3.1.0
  flutter_screenutil: ^5.3.1
  smooth_page_indicator: ^1.0.0+2
  cached_network_image: ^3.2.0
  readmore: ^2.1.0
  change_notifier: ^0.24.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.5.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  stream_transform: ^2.0.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  retrofit_generator: '>=4.0.0 <5.0.0'
  hive_generator: ^1.1.2
  json_serializable: ^6.2.0


flutter:
  assets:
    - assets/translations/
    - assets/images/
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
